config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"


  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :show, :index]
    resources :tasks, only: [:index, :show, :update, :create, :destroy]
    resource  :session, only: [:show, :create, :destroy]
    resources :invites, only: [:create]
    resources :projects, only: [:create, :index, :show]
    resources :comments, only: [:create, :delete]

    get 'tasks/project_tasks/:project_id', to: 'tasks#project_tasks'
    patch 'tasks/reorder/:id', to: 'tasks#reorder'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :ensure_session_token
  before_save :downcase_email_remove_whitespace
  validates :email, :name, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true

  has_attached_file :avatar, default_url: 'http://schemeapp.com/assets/avatar-placeholder-3457dd70fea884c004730991df531cc8eb7d4b9abaca82d5e1b6aff46dde79e9.png';
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many(
    :tasks,
    class_name: 'Task',
    primary_key: :id,
    foreign_key: :creator_id
  )

  has_one(
    :membership,
    class_name: 'Membership',
    primary_key: :id,
    foreign_key: :member_id
  )

  has_one(
    :team,
    through: :membership,
    source: :team
  )

  has_many(
    :teammates,
    through: :team,
    source: :members
  )

  has_many(
    :teammate_tasks,
    through: :team,
    source: :tasks
  )

  has_many(
    :projects,
    through: :team,
    source: :projects
  )

  has_many :task_comments


  attr_reader :password

  def password=(password)
    @password = password.strip
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password.strip)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email.downcase.strip)
    return nil unless user

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save!
  end

  # return's tasks created by user & user's teammates
  def all_team_tasks
    self.teammate_tasks + self.tasks
  end

  private
    def ensure_session_token
      self.session_token ||= SecureRandom.urlsafe_base64
    end

    def downcase_email_remove_whitespace
      self.email = self.email.downcase.strip unless self.email.nil?
    end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @users = current_user.teammates
    render :index
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      accept_invite_or_create_new_team(@user)
      render json: @user
    else
      render json: { message: "Invalid credentials" }, status: 401
    end
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end

  def seed_tasks_for_user(user)
    4.times do
      task = user.tasks.new
      task.name = Faker::Company.bs
      task.description =
        [Faker::Hacker.say_something_smart,
          Faker::Hacker.say_something_smart,
          Faker::Hacker.say_something_smart].join(" ")
      task.assignee_id = user.id
      task.deadline = Date.today + rand(14).days
      task.save!
    end
  end

  def accept_invite_or_create_new_team(user)
    invite = Invite.find_by(email: user.email)
    if invite
      Membership.create(member_id: user.id, team_id: invite.team_id)
      invite.replied = true
      invite.save
    else
      team = Team.create(creator_id: user.id, name: user.name + "'s Workspace")
      Membership.create(member_id: user.id, team_id: team.id)
      team.projects.create(name: user.name + "'s Tasks")
      seed_tasks_for_user(user)
    end
  end
end

app/controllers/users_controller.rb
# class Api::UsersController < ApplicationController

#   def create
#     @user = User.new(user_params)

#     if @user.save
#       login!(@user)
#       render json: user
#     else
#       render json: { message: "Invalid credentials" }, status: 401
#     end
#   end

#   def show
#     @user = User.find(params[:id])
#     render json: user
#   end

#   private
#   def user_params
#     params.require(:user).permit(:name, :email, :password, :avatar)
#   end
# end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="auth-fullscreen">

  <div class="login-logo">
    <img src="<%= asset_url('scheme_logo.png') %>" />
  </div>

  <div class="group auth-dialog">

    <h1>Please start by completing your profile.</h1>

    <form action="<%= users_url %>" method="POST">
      <%= auth_token %>

      <div class="upload-div">
        <p>Add Photo</p>
      </div>

      <div class="input">
        <label for="name">Full Name</label><br />
        <input type="text" name="user[name]" id="name" />
      </div>

      <div class="input">
        <label for="email">Work Email</label><br />
        <input type="email" name="user[email]" id="email" />
        <svg class="confirm" viewBox="0 0 32 32">
          <polygon points="30,5.077 26,2 11.5,22.5 4.5,15.5 1,19 12,30"></polygon>
        </svg>
      </div>

      <div class="input password">
        <label for="password">Password</label><br />
        <input type="password" name="user[password]" id="password" />
      </div>

      <div class="submit">
        <button>Continue</button>
      </div>
    </form>
  </div>

  <footer class="group registration">
    <ul>
      <li><a href="#">About Scheme</a></li>
      <li><a href="http://jordanholliday.com">Blog</a></li>
    </ul>
    <div class="toggle-auth">
      Got an account?
      <a href="<%= new_session_url %>" class="button">Log In</a>
    <div>
  </footer>

</div>

app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= my_delete_button("log out", session_url) %></p>